version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: chat-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chat_db

  api:
    build: .
    container_name: chat-api
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongo:27017
      DATABASE_NAME: chat_db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  mongo_data: 